apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: mealie

  template:
    metadata:
      labels:
        app: mealie
        network-policy-type: app

    spec:
      securityContext:
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911

      imagePullSecrets:
        - name: harbor-registry-creds

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.21.0

          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 600Mi

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: mealie-configmap
            - secretRef:
                name: mealie-app-secrets
            - secretRef:
                name: mealie-openai-secrets

          ports:
            - containerPort: 9000
              protocol: TCP

          volumeMounts:
            - name: mealie-data
              mountPath: /app/data

      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc

      restartPolicy: Always
